#GET https://color-extractor-api-jr6v-dev.fl0.io/

POST https://color-extractor-api-jr6v-dev.fl0.io/images/

{
    "name": "hamburger",
    "ext": "jpg",
    "url": "https://natashaskitchen.com/wp-content/uploads/2023/06/Cheeseburger.jpg"
}